services:
  - type: web
    name: teen-patti-pool
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: false
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
